### ISSUE TITLE
proxy via another go-lang server 

### ISSUE THREAD

**Issue by necrose99** [fragmenta/server#5]
https://github.com/mholt/caddy  or other webdav enabled server ... 
https://gpo.zugaina.org/www-servers/caddy

https://github.com/gowncloud/gowncloud / https://github.com/cockroachdb/cockroach (might be a nice drop in for Frag also )  dev-db/cockroach (https://gpo.zugaina.org/dev-db/cockroach)

mainly it would be nice to have a **single master server** , with a few nice to have add ons ie 
webdav/sftp/ssh-fs   for a few dir's note related to CMS  ie Package/dirs for binaries and xfers for those.. 
and pipe the traffic via config file .. to master via 8080 or other ports poxy ..  and hook it to main.. as Virtual site..  **for Frag.. as main CMS ..** 

so far with smaller testing , it builds on debian/gentoo arm64 , windows , gentoo x64 ..
add multiple products , as a security admin i do like the low hackability foot print ,
and less php cluster fubar deps hell...     add on a chroot for  pkg builds not much room on host instance for much else.  size footprint is good.

**Comment by kennygrant** [comment]
Thanks for the suggestion, you can already run fragmenta behind various proxies (nginx, caddy), or run it standalone. I've done this myself in the past, though nowadays tend to run it standalone. I think I'd rather concentrate on running it as a standalone server which supports ssl via letsencrypt though, rather than any integrations with caddy, so I'm going to close this one as won't fix I'm afraid. 

I would like to explore using a go database to remove that dependency, but have a separate issue about that open on the cms.
