### ISSUE TITLE
Config Package Not Generic for Custom Config Files

### ISSUE THREAD

**Issue by MostafaGamal** [fragmenta/server#6]
I've tried to use the config package to make my own configuration file, such file doesn't need to have environments, think of it as file for messages or locales file
 that has no environments as in assets.json file

First of all: in the Load() function in config.go the configurations for the 3 different environments [development, production & test] are loaded, following such pattern would force the user to create those 3 environments in his/ her new config file.

2nd: and please correct me if I'm wrong,  loading those 3 environments might not be needed. There could be some condition that checks what is the current running environment and then load its keys/values only to config map.

3rd: the current implementation of loading configurations has some variable named "current" that can point to just one file, is there an ability to make it bit scalable to load more than one file simultaneously? So that both files are used and pointed to in the runtime.
Thanks in advance.

**Comment by kennygrant** [comment]
This package isn't really intended as a general purpose config package, so I'm afraid there are some assumptions baked in. There are some other packages which attempt to offer loading of arbitrary config files, so those might be a better starting point, or you could fork this and relatively easily remove the assumptions. 

1. Some assumptions are made about which environments are available, in order to offer convenience functions and ensure correct formatting of the config file to run tests etc - fragmenta does require the three configs in order to separate development, test and production environments. 
2. It's not necessary to load all three configs, but it is useful sometimes as it allows you to switch configs within the app if. The extra memory used is negligible so I think better to have the convenience. 
3. The Current pkg global just makes it easier for apps. There is no requirement to use it. Again though this makes assumptions about usage - if you need a config package which handles lots of files for some reason (which wouldn't work with fragmenta), I'd suggest creating a new one either based on this or other config packages. 

If loading a locales file or messages, I would consider creating your own package which loads the format you want - having a specific loader tailored to the type of data makes more sense (for example translations you probably want to load multiple files keyed on language and keep in memory). So I'm going to close this issue as I don't anticipate trying to make this a generic json loading package rather than a tool to load fragmenta configs.
